Alireza/ai 278/add forever broker reconnection config
SolaceDev/solace-ai-connector pull request #77
Opened 2024-12-16 20:38 UTC by alimosaed

**What is the purpose of this change?**
If the broker disconnects, the connector will attempt to reconnect for up to 1 minute. If it fails to reconnect within that time, it will stop trying.

**How is this accomplished?**
The connector currently uses a parameterized retry policy, which retries a specified number of times to reconnect. This PR adds a “forever” retry policy, which continuously attempts to reconnect at fixed time intervals.

**Anything reviews should focus on/be aware of?**

2025-01-17 18:12 UTC, gregmeldrum approved these changes
Looks good!

2025-01-17 18:48 UTC, cyrus2281 approved these changes
Code looks good.

Added a request regarding the example

2025-01-17 18:48 UTC, cyrus2281 commented on examples/llm/litellm_chat.yaml
> +      retry_interval: 1000 # in milliseconds
Why the connection example is added to LiteLLM example? Can we move this to an example that is dedicated for solace broker connection (if we don't already have one, maybe a new example under the `examples/solace_input_output.yaml`

2025-01-17 18:49 UTC, cyrus2281 requested changes
Actually documentation needs to be updated. 

You need to add the new configs to the component info and then run the doc generate command

2025-01-20 14:11 UTC, alimosaed commented on examples/llm/litellm_chat.yaml
> +      retry_interval: 1000 # in milliseconds
Moved the new settings to a new yaml file.

2025-01-20 16:30 UTC, alimosaed reviewed
- Moved the reconnection settings to a new `broker_input_output.yaml` file.
- Refactored the broker configurations and moved common settings to the broker_base.py
- Generate documents


Ready for review

2025-01-20 19:03 UTC, cyrus2281 approved these changes
Looks awesome, thanks!

2025-01-20 21:16 UTC, merged